
const form = document.querySelector('#searchLocation');
const input = document.querySelector('#searchInput');
const submitButton = document.querySelector('#submitButton');
const locations = document.querySelector('#locations');
let fahrenheit = document.querySelector('#tempF');
let celsius = document.querySelector('#tempC');
let city = document.querySelector('#cityName');
let state = document.querySelector('#stateName');
let country = document.querySelector('#countryName');

const APIKey = '77e6d6f2ccba402f96e221603230803';

form.addEventListener('submit', async function (event) {
    event.preventDefault();
    const query = input.value;
    const configuration = { params: { q: query, key: APIKey } }
    // We could also just use the built in fetch function honestly
    axios.get(`http://api.weatherapi.com/v1/current.json?`, configuration)
        .then(function (response) {
            addLocationToScreen(response.data);
        })
        .catch(function (error) {
            console.log(error);
        })
});

const addLocationToScreen = (locationInput) => {

    fahrenheit.textContent = locationInput.current.temp_f;
    celsius.textContent = locationInput.current.temp_c;
    city.textContent = locationInput.location.name;
    state.textContent = locationInput.location.region;
    country.textContent = locationInput.location.country;
    input.value = "";

}


/*
const form = document.querySelector('#searchForm');
form.addEventListener('submit', async function (e) {
    e.preventDefault();
    const searchTerm = form.elements.query.value;
    // for if we needed just one or so inputs
    // const res = await axios.get(`https://api.tvmaze.com/search/shows?q=${searchTerm}`);
    // for if we had multiple types of search inputs
    const config = { params: { q: searchTerm } }
    const res = await axios.get(`https://api.tvmaze.com/search/shows`, config);
    makeImages(res.data)
    form.elements.query.value = "";

})

const makeImages = (shows) => {
    for (let result of shows) {
        if (result.show.image) {
            const img = document.createElement('img');
            img.src = result.show.image.medium;
            document.body.append(img)
        }

    }
}
*/
















/*  This part was generated by the bing chat thing
< form id="search-form" >
    <input type="text" id="search-input" placeholder="Enter a location">
        <button type="submit" id="search-button">Search</button>
</form>

// Get the elements from the document
const form = document.getElementById('search-form');
const input = document.getElementById('search-input');
const button = document.getElementById('search-button');

// Add an event listener to the form submit event
form.addEventListener('submit', function (event) {
    // Prevent the default behavior of reloading the page
    event.preventDefault();

    // Get the value of the input
    const query = input.value;

    // Make sure the query is not empty
    if (query) {
        // Make an axios request to the API with your API key and query
        axios.get(`http://api.weatherapi.com/v1/current.json?key=YOUR_API_KEY&q=${query}`)
            .then(function (response) {
                // Handle the response data here
                console.log(response.data);
            })
            .catch(function (error) {
                // Handle any errors here
                console.error(error);
            });
    }
});
*/